### ISSUE TITLE
Issues with fastdl

### ISSUE THREAD

**Issue by Spaenny** [melkortf/tf2-servers#127]
People have been reporting to me that the current fastdl: "https://dl.serveme.tf/maps" causes issues for them, maps are not being downloaded. When I checked you get a 301 from the URL redirecting you to "https://fastdl.serveme.tf/maps". When I changed the URL for my services people reported it worked without any issue, I assume the TF2 Client does not know how to handle being redirected, we should update to the new URL.

**Comment by garrappachc** [comment]
Yup, you're correct, will be fixed. Thanks!
