### ISSUE TITLE
Add OverlayFS support to do runtime layering

### ISSUE THREAD

**Issue by stevefan1999-personal** [melkortf/tf2-servers#142]
It is something like this: https://www.baeldung.com/linux/overlayfs-usage

For example, we have can have a special folder called `tf2-overlay` and then it will merge the content into the `tf2` folder, so we can cleanly separate custom assets (such as sound, materials, maps and models) into a different folder that is ReadWriteMany shared in Kubernetes.

If native overlayfs support was not detected, we have to fall back to use fuse-overlayfs: https://github.com/containers/fuse-overlayfs.

Of course, another way to do it is to just embed those assets into the container images themselves. 

```dockerfile
FROM ghcr.io/melkortf/tf2-base:latest
COPY ./models/ tf2/models
COPY ./sounds/ tf2/sounds
...
```

But it comes with a cost of having to constantly track upstream image new version and I kind of hate to have a cron job for doing this when I can just have a minimal set of image that can quickly onboard a new node and share those assets with Ceph or NFS.

And worse, in containers, only the layers above can be shared, and every time I add my 20GB+ assets into the image, it is effectively duplicated again and causing a lot of disk problem (since I always have to start again with the latest base image).

**Comment by garrappachc** [comment]
I'll look into it with more depth, but for the moment: have you tried the [podman's -O option](https://docs.podman.io/en/latest/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options) or [docker's --mount](https://docs.docker.com/reference/cli/docker/container/run/#mount)?

**Comment by stevefan1999-personal** [comment]
> I'll look into it with more depth, but for the moment: have you tried the [podman's -O option](https://docs.podman.io/en/latest/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options) or [docker's --mount](https://docs.docker.com/reference/cli/docker/container/run/#mount)?

I'm not using podman nor docker. I'm using Kubernetes
