### ISSUE TITLE
Add TF2 Brazilian League Configs

### ISSUE THREAD

**Issue by galdoway** [melkortf/tf2-servers#186]
Hey! 
I would like to contribute to the TF2 Competitive Docker image by adding configs and whitelists for the [Brazilian TF2 league (FTBF)](https://fbtf.tf/). Brazil has the largest competitive TF2 community in South America, and adding support for FTBF would help expand the usage of this Docker image within the community.

I've reviewed the Docker image structure and I can submit a pull request that aligns with its standards. Please let me know if there are any specific requirements or preferences for including these configs.

Thank you for considering this contribution!

**Comment by garrappachc** [comment]
Hi!
Please submit a PR and I'll take a look at it in my spare time. The image being affected will be `tf2-competitive`.
Don't commit the configs to the repository - instead, make Dockerfile download the configs and put them in the proper directory during the build time. MD5 checksums are to make sure nobody is able to inject malicious content into the final image.
If possible, please make versioning possible. It's easily done through git tags and GitHub releases.
Feel free to ask any questions :)

**Comment by galdoway** [comment]
Here is the link to the pull request :)

https://github.com/melkortf/tf2-servers/pull/187
