### ISSUE TITLE
Slot amount hardcoded

### ISSUE THREAD

**Issue by Spaenny** [melkortf/tf2-servers#3]
https://github.com/melkortf/tf2-servers/blob/a39647aae05e175cda0d906f62ba23231cca8480/packages/tf2-base/Dockerfile#L72

Why exactly is the slot amount hardcoded?
Couldn't this be solved with using a shell form of the entrypoint, as documented here?
https://docs.docker.com/engine/reference/builder/#entrypoint

**Comment by garrappachc** [comment]
The entrypoint is there, it just covers the essential arguments passed to `srcds_run`. You can override the +maxplayers argument by overriding the command in `docker run`, for example:
```
docker run -itd --network=host melkortf/tf2-base +sv_pure 2 +map cp_process_final +maxplayers 32
```
