### ISSUE TITLE
[Request] Mapcycle Variable

### ISSUE THREAD

**Issue by Gnomesenpai** [melkortf/tf2-servers#75]
Enviroment variable for chosing map cycle would be handy!

**Comment by Spaenny** [comment]
I think doing this over an Enviroment variable isn't the best way. I just use a volume with my mapcycle.txt mounted in the docker container.

**Comment by garrappachc** [comment]
How would that environment variable work? What would it look like?

**Comment by Spaenny** [comment]
I'm not too sure either, best we could do is some environment variable point to a different mapcycle file? Otherwise we would have to deal with newlines in environment variables, or write something fancy to untangle it.
