### ISSUE TITLE
TF2 Update broke everything

### ISSUE THREAD

**Issue by Spaenny** [melkortf/tf2-servers#83]
We need to bump SourceMod to the new version, when the issue got fixed.
https://github.com/alliedmodders/hl2sdk/pull/120

**Comment by sapphonie** [comment]
its fixed

**Comment by Spaenny** [comment]
Thanks Sappho!

**Comment by Spaenny** [comment]
We also need to bump tf2-comp-fixes to 1.16.11, there have been changes to gamedata.
https://github.com/ldesgoui/tf2-comp-fixes/releases/tag/v1.16.11
