### ISSUE TITLE
20 March 2023 Update breaks client compatibility

### ISSUE THREAD

**Issue by freerainboxbox** [melkortf/tf2-servers#98]
Images should be updated accordingly. Should be a simple update: repackage the image, and freshen up the checksums.

**Comment by freerainboxbox** [comment]
> What do you mean by "client"? TF2 itself updates upon launch just fine, all checksums are also good.

Client is new, server is not. Docker image isn't the newest version. Pulling the image again and running it doesn't show the newest version.

**Comment by freerainboxbox** [comment]
I found the issue. When running the docker image, `ghcr.io/` must be before the image name. Otherwise an old version is run. For example: `docker run <...> ghcr.io/melkortf/tf2-base`.

**Comment by garrappachc** [comment]
Yeah, I mentioned it in the [3.0.0 release docs](https://github.com/melkortf/tf2-servers/releases/tag/3.0.0); I moved the images from Docker registry to the GitHub's one.
